ARG php_version="?.?.?"
ARG xp_version="?.?.?"

FROM lambda-xp-runtime:${php_version} as runtime

FROM lambci/lambda:provided

COPY --from=runtime /opt/php/bin/ /opt/bin/

COPY --from=runtime /opt/php/bootstrap /opt/bootstrap

COPY --from=runtime /usr/lib64/libonig.so.2 /opt/bin

ENV LD_LIBRARY_PATH=/opt/bin/

ENV TZ UTC