ARG php_version="?.?.?"
ARG xp_version="?.?.?"

FROM lambda-xp-runtime:${php_version} as runtime

FROM lambci/lambda:provided

COPY --from=runtime /opt/php/bin/ /opt/bin/

COPY --from=runtime /opt/php/bootstrap /opt/bootstrap

ENV TZ UTC